apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webapp-pod
  name: webapp-pod
spec:
  containers:
  - image: nancolor/for-lab-dos
    name: webapp-pod
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
